server:
  port: 8902
  

spring:
# druid , FOR WRITING DB
  datasource:
    master-db:
      name: masterDb
      url: jdbc:mysql://172.10.28.8:3306/db_b?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: password
      #type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver    
      #最大活跃数
      maxActive: 20
      #初始化数量
      initialSize: 1
      #配置获取连接等待超时的时间
      maxWait: 60000
      minIdle: 1
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      #配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000  

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000 #默认：（方法上记得要加上@HystrixCommand，否则无效）
#          strategy: SEMAPHORE
feign:
  hystrix:
    enabled: true 
              
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
  #https://github.com/spring-cloud/spring-cloud-security/issues/61
  http:
    client:
      enabled: true  

#HystrixDashboard
management:
  endpoints:
    web:
      exposure:
        #include: hystrix.stream, info, health
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
      #base-path: actuator //by default


redtx:
  client:
    tx-timeout: 30000
    mgrAddrs: ${REDTX_SERVER:172.10.1.63:9011}
